"""Add password reset tokens table

Revision ID: bcb99b11b6d5
Revises: 39e13d91f835
Create Date: 2025-12-19 13:12:36.369234+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcb99b11b6d5'
down_revision: Union[str, None] = '39e13d91f835'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_reset_tokens',
    sa.Column('token_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core_app.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_id'),
    schema='core_app'
    )
    op.create_index(op.f('ix_core_app_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'], unique=True, schema='core_app')
    op.create_index(op.f('ix_core_app_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False, schema='core_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_app_password_reset_tokens_user_id'), table_name='password_reset_tokens', schema='core_app')
    op.drop_index(op.f('ix_core_app_password_reset_tokens_token_hash'), table_name='password_reset_tokens', schema='core_app')
    op.drop_table('password_reset_tokens', schema='core_app')
    # ### end Alembic commands ###
