"""create_core_app_tables

Revision ID: c32835a4b99d
Revises: 
Create Date: 2025-12-18 14:41:58.743037+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c32835a4b99d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('role_id'),
    schema='core_app'
    )
    op.create_index(op.f('ix_core_app_roles_role_name'), 'roles', ['role_name'], unique=True, schema='core_app')
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    schema='core_app'
    )
    op.create_index(op.f('ix_core_app_users_email'), 'users', ['email'], unique=True, schema='core_app')
    op.create_index(op.f('ix_core_app_users_username'), 'users', ['username'], unique=True, schema='core_app')
    op.create_table('workflows',
    sa.Column('workflow_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('workflow_name', sa.String(length=100), nullable=False),
    sa.Column('workflow_code', sa.String(length=50), nullable=False),
    sa.Column('schema_name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('workflow_id'),
    sa.UniqueConstraint('schema_name'),
    schema='core_app'
    )
    op.create_index(op.f('ix_core_app_workflows_workflow_code'), 'workflows', ['workflow_code'], unique=True, schema='core_app')
    op.create_table('audit_logs',
    sa.Column('log_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('workflow_schema', sa.String(length=50), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('changes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['core_app.users.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('log_id'),
    schema='core_app'
    )
    op.create_index(op.f('ix_core_app_audit_logs_action_type'), 'audit_logs', ['action_type'], unique=False, schema='core_app')
    op.create_index(op.f('ix_core_app_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False, schema='core_app')
    op.create_index(op.f('ix_core_app_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False, schema='core_app')
    op.create_index(op.f('ix_core_app_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False, schema='core_app')
    op.create_index(op.f('ix_core_app_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False, schema='core_app')
    op.create_index(op.f('ix_core_app_audit_logs_workflow_schema'), 'audit_logs', ['workflow_schema'], unique=False, schema='core_app')
    op.create_table('data_exports',
    sa.Column('export_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('workflow_schema', sa.String(length=50), nullable=False),
    sa.Column('export_type', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('filters_applied', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('record_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core_app.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('export_id'),
    schema='core_app'
    )
    op.create_index(op.f('ix_core_app_data_exports_created_at'), 'data_exports', ['created_at'], unique=False, schema='core_app')
    op.create_index(op.f('ix_core_app_data_exports_expires_at'), 'data_exports', ['expires_at'], unique=False, schema='core_app')
    op.create_index(op.f('ix_core_app_data_exports_user_id'), 'data_exports', ['user_id'], unique=False, schema='core_app')
    op.create_table('two_factor_auth',
    sa.Column('tfa_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret_key', sa.String(length=255), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('backup_codes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core_app.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tfa_id'),
    schema='core_app'
    )
    op.create_index(op.f('ix_core_app_two_factor_auth_user_id'), 'two_factor_auth', ['user_id'], unique=True, schema='core_app')
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['core_app.users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['core_app.roles.role_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['core_app.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id'),
    schema='core_app'
    )
    op.create_table('user_sessions',
    sa.Column('session_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_activity_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['core_app.users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id'),
    schema='core_app'
    )
    op.create_index(op.f('ix_core_app_user_sessions_expires_at'), 'user_sessions', ['expires_at'], unique=False, schema='core_app')
    op.create_index(op.f('ix_core_app_user_sessions_refresh_token'), 'user_sessions', ['refresh_token'], unique=True, schema='core_app')
    op.create_index(op.f('ix_core_app_user_sessions_session_token'), 'user_sessions', ['session_token'], unique=True, schema='core_app')
    op.create_index(op.f('ix_core_app_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False, schema='core_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_core_app_user_sessions_user_id'), table_name='user_sessions', schema='core_app')
    op.drop_index(op.f('ix_core_app_user_sessions_session_token'), table_name='user_sessions', schema='core_app')
    op.drop_index(op.f('ix_core_app_user_sessions_refresh_token'), table_name='user_sessions', schema='core_app')
    op.drop_index(op.f('ix_core_app_user_sessions_expires_at'), table_name='user_sessions', schema='core_app')
    op.drop_table('user_sessions', schema='core_app')
    op.drop_table('user_roles', schema='core_app')
    op.drop_index(op.f('ix_core_app_two_factor_auth_user_id'), table_name='two_factor_auth', schema='core_app')
    op.drop_table('two_factor_auth', schema='core_app')
    op.drop_index(op.f('ix_core_app_data_exports_user_id'), table_name='data_exports', schema='core_app')
    op.drop_index(op.f('ix_core_app_data_exports_expires_at'), table_name='data_exports', schema='core_app')
    op.drop_index(op.f('ix_core_app_data_exports_created_at'), table_name='data_exports', schema='core_app')
    op.drop_table('data_exports', schema='core_app')
    op.drop_index(op.f('ix_core_app_audit_logs_workflow_schema'), table_name='audit_logs', schema='core_app')
    op.drop_index(op.f('ix_core_app_audit_logs_user_id'), table_name='audit_logs', schema='core_app')
    op.drop_index(op.f('ix_core_app_audit_logs_entity_type'), table_name='audit_logs', schema='core_app')
    op.drop_index(op.f('ix_core_app_audit_logs_entity_id'), table_name='audit_logs', schema='core_app')
    op.drop_index(op.f('ix_core_app_audit_logs_created_at'), table_name='audit_logs', schema='core_app')
    op.drop_index(op.f('ix_core_app_audit_logs_action_type'), table_name='audit_logs', schema='core_app')
    op.drop_table('audit_logs', schema='core_app')
    op.drop_index(op.f('ix_core_app_workflows_workflow_code'), table_name='workflows', schema='core_app')
    op.drop_table('workflows', schema='core_app')
    op.drop_index(op.f('ix_core_app_users_username'), table_name='users', schema='core_app')
    op.drop_index(op.f('ix_core_app_users_email'), table_name='users', schema='core_app')
    op.drop_table('users', schema='core_app')
    op.drop_index(op.f('ix_core_app_roles_role_name'), table_name='roles', schema='core_app')
    op.drop_table('roles', schema='core_app')
    # ### end Alembic commands ###
