"""add_user_is_verified_and_two_factor_enabled

Revision ID: e1c4956ec992
Revises: c32835a4b99d
Create Date: 2025-12-18 15:17:45.982088+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c4956ec992'
down_revision: Union[str, None] = 'c32835a4b99d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False), schema='core_app')
    op.add_column('users', sa.Column('two_factor_enabled', sa.Boolean(), nullable=False), schema='core_app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_enabled', schema='core_app')
    op.drop_column('users', 'is_verified', schema='core_app')
    # ### end Alembic commands ###
