"""
Shared Utilities

Common utilities used across core and workflow modules.
"""

from app.shared.exceptions import (
    AppException,
    UnauthorizedException,
    InvalidCredentialsException,
    TokenExpiredException,
    TokenInvalidException,
    SessionExpiredException,
    SessionRevokedException,
    ForbiddenException,
    InsufficientPermissionsException,
    ValidationException,
    InvalidInputException,
    NotFoundException,
    AlreadyExistsException,
    ConflictException,
    TwoFactorRequiredException,
    TwoFactorInvalidException,
    TwoFactorNotEnabledException,
    AccountLockedException,
    AccountDisabledException,
    RateLimitExceededException,
    InternalErrorException,
    DatabaseErrorException,
    ServiceUnavailableException,
)
from app.shared.pagination import (
    PaginationParams,
    PaginatedResult,
    get_pagination_params,
    paginate_query,
    paginate_list,
)
from app.shared.responses import (
    ErrorCodes,
    ErrorDetail,
    SuccessResponse,
    ErrorResponse,
    PaginatedResponse,
    PaginationMeta,
    success_response,
    error_response,
    paginated_response,
)
from app.shared.security import (
    hash_password,
    verify_password,
    create_access_token,
    create_refresh_token,
    decode_token,
    verify_token,
    generate_token_id,
    generate_session_token,
    generate_password_reset_token,
    extract_token_from_header,
    TokenType,
)
from app.shared.validators import (
    validate_email,
    validate_password,
    validate_username,
    validate_phone_number,
    validate_name,
    validate_registration_data,
    is_valid_email,
    is_valid_password,
    is_valid_username,
    get_password_strength,
)

__all__ = [
    # Exceptions
    "AppException",
    "UnauthorizedException",
    "InvalidCredentialsException",
    "TokenExpiredException",
    "TokenInvalidException",
    "SessionExpiredException",
    "SessionRevokedException",
    "ForbiddenException",
    "InsufficientPermissionsException",
    "ValidationException",
    "InvalidInputException",
    "NotFoundException",
    "AlreadyExistsException",
    "ConflictException",
    "TwoFactorRequiredException",
    "TwoFactorInvalidException",
    "TwoFactorNotEnabledException",
    "AccountLockedException",
    "AccountDisabledException",
    "RateLimitExceededException",
    "InternalErrorException",
    "DatabaseErrorException",
    "ServiceUnavailableException",
    # Pagination
    "PaginationParams",
    "PaginatedResult",
    "get_pagination_params",
    "paginate_query",
    "paginate_list",
    # Responses
    "ErrorCodes",
    "ErrorDetail",
    "SuccessResponse",
    "ErrorResponse",
    "PaginatedResponse",
    "PaginationMeta",
    "success_response",
    "error_response",
    "paginated_response",
    # Security
    "hash_password",
    "verify_password",
    "create_access_token",
    "create_refresh_token",
    "decode_token",
    "verify_token",
    "generate_token_id",
    "generate_session_token",
    "generate_password_reset_token",
    "extract_token_from_header",
    "TokenType",
    # Validators
    "validate_email",
    "validate_password",
    "validate_username",
    "validate_phone_number",
    "validate_name",
    "validate_registration_data",
    "is_valid_email",
    "is_valid_password",
    "is_valid_username",
    "get_password_strength",
]
